# Generated by Django 5.0.6 on 2024-06-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsmoms_app', '0002_alter_customuser_user_type_alter_doctor_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='admin',
            new_name='user',
        ),
    ]
