# Generated by Django 5.0.6 on 2024-06-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsmoms_app', '0003_rename_admin_patient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='admin',
        ),
    ]
