# Generated by Django 5.0.6 on 2024-06-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsmoms_app', '0004_rename_user_patient_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='first_name',
            field=models.CharField(default='ry', max_length=30),
        ),
    ]
