# Generated by Django 5.0.6 on 2024-06-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsmoms_app', '0005_receptionist_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='ry', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='ry', max_length=30),
        ),
    ]
