# Generated by Django 5.0.6 on 2024-06-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsmoms_app', '0006_doctor_first_name_patient_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionfeedback',
            name='status',
            field=models.CharField(default='unviewed', max_length=30),
        ),
    ]
