# Generated by Django 5.0.6 on 2024-06-15 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsmoms_app', '0009_alter_appointment_status_alter_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='disease',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='illnes',
            field=models.CharField(default='fever', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medical_history_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsmoms_app.medicalhistory'),
        ),
    ]
