# Generated by Django 5.0.6 on 2024-06-15 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsmoms_app', '0010_remove_prescription_disease_medicalhistory_illnes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='doctor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsmoms_app.doctor'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='patient_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsmoms_app.patient'),
        ),
    ]
