# Generated by Django 5.0.6 on 2024-06-15 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsmoms_app', '0011_remove_prescription_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionfeedback',
            name='patient_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsmoms_app.patient'),
        ),
    ]
