# Generated by Django 5.0.6 on 2024-06-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsmoms_app', '0012_prescriptionfeedback_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='status',
            field=models.CharField(default='unprescribed', max_length=30),
        ),
    ]
