from django.urls import path
from .import views, admin_views, patient_views, doctor_views, receptionist_views

urlpatterns = [
    path('', views.home, name='home'),
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('patient/register/', views.patient_register, name='patient_register'),
    path('login_as_Admin/', views.admin_login, name='admin_login'),
    path('doctor_dashboard/', views.doctor_dashboard, name='doctor_dashboard'),
    path('patient_dashboard/', views.patient_dashboard, name='patient_dashboard'),
    path('receptionist_dashboard/', views.receptionist_dashboard, name='receptionist_dashboard'),
    path('admin-dashboard/', admin_views.admin_dashboard, name='admin_dashboard'),
    path('admin_logout/', views.admin_logout, name='admin_logout'), 
    path('logout/', views.logout_view, name='logout'), 

# admin urls 
    path('admin-dashboard/manage_doctors/', admin_views.manage_doctors, name='manage_doctors'),
    path('admin-dashboard/manage_receptionists/', admin_views.manage_receptionists, name='manage_receptionists'),
    path('admin-dashboard/create_receptionist/', admin_views.create_receptionist, name='create_receptionist'),
    path('admin-dashboard/edit_receptionist/<int:pk>/', admin_views.edit_receptionist, name='edit_receptionist'),
    path('admin-dashboard/delete_receptionist/<int:pk>/', admin_views.delete_receptionist, name='delete_receptionist'),
    path('admin-dashboard/create_doctor/', admin_views.create_doctor, name='create_doctor'),
    path('admin-dashboard/manage_specialization/', admin_views.manage_specialization, name='manage_specialization'),
    path('admin-dashboard/edit_specialization/<int:pk>/', admin_views.edit_specialization, name='edit_specialization'),
    path('admin-dashboard/delete_specialization/<int:pk>/', admin_views.delete_specialization, name='delete_specialization'),
    path('admin-dashboard/manage_schedule/', admin_views.manage_schedule, name='manage_schedule'),
    path('admin-dashboard/add_schedule/', admin_views.add_schedule, name='add_schedule'),
    path('admin-dashboard/edit_schedule/<int:pk>/', admin_views.edit_schedule, name='edit_schedule'),
    path('admin-dashboard/delete_schedule/<int:pk>/', admin_views.delete_schedule, name='delete_schedule'),
    path('admin-dashboard/edit_doctor/<int:pk>/', admin_views.edit_doctor, name='edit_doctor'),
    path('admin-dashboard/delete_doctor/<int:pk>/', admin_views.delete_doctor, name='delete_doctor'),
    path('admin-dashboard/manage_patients/', admin_views.manage_patients, name='manage_patients'),
    path('admin-dashboard/edit_patient/<int:pk>/', admin_views.edit_patient, name='edit_patient'),
    path('admin-dashboard/delete_patient/<int:pk>/', admin_views.delete_patient, name='delete_patient'),
    path('admin-dashboard/view_appointments/', admin_views.view_appointments, name='view_appointments'),
    path('admin-dashboard/view_prescriptions/', admin_views.view_prescriptions, name='view_prescriptions'),
    path('admin-dashboard/view_reports/', admin_views.view_reports, name='view_reports'),
    path('admin-dashboard/patient_feedback/on_precrisptions/', admin_views.feedback_on_prescriptions, name='feedback_on_prescriptions'),


# doctor urls
    path('doctor/view_appointments/', doctor_views.view_appointments, name='doc_view_appointments'),
    path('doctor/confirm_appointment/<int:pk>/', doctor_views.confirm_appointment, name='doc_confirm_appointment'),
    path('doctor/cancel_appointment/<int:pk>/', doctor_views.cancel_appointment, name='doc_cancel_appointment'),
    path('doctor/view_patients/', doctor_views.view_patients, name='doc_view_patients'),
    path('doctor/view_medical_records/', doctor_views.view_medical_records, name='doc_view_medical_records'),
    path('doctor/add_medical_records/<int:pk>/', doctor_views.add_medical_records, name='add_medical_records'),
    path('doctor/add_prescriptions/<int:pk>/', doctor_views.add_prescription, name='add_prescription'),
    path('doctor/change_prescriptions/<int:pk>/', doctor_views.change_prescription, name='change_prescription'),
    path('doctor/completed_prescription/<int:pk>/', doctor_views.completed_prescription, name='completed_prescription'),
    path('doctor/completed_newprescription/<int:pk>/', doctor_views.completed_newprescription, name='completed_newprescription'),
    path('doctor/view_prescriptions/', doctor_views.view_prescriptions, name='doc_view_prescriptions'),
    path('doctor/view_changed_prescriptions/', doctor_views.view_changed_pres, name='doc_view_changed_pres'),
    path('doctor/create_report/', doctor_views.create_report, name='doc_create_report'),
    path('doctor/manage_reports/', doctor_views.manage_reports, name='doc_manage_reports'),
    path('doctor/edit_weekly_report/<int:pk>/', doctor_views.edit_weekly_report, name='edit_weekly_report'),
    path('doctor/my_profile/', doctor_views.my_profile, name='doc_my_profile'),
    path('doctor/change_password/', doctor_views.change_password, name='doc_change_password'),
    path('doctor/patient_feedback/', doctor_views.patient_feedback, name='doc_patient_feedback'),
    path('doctor/viewed_feedback/<int:pk>/', doctor_views.viewed_feedback, name='viewed_feedback'),
    

# patient urls
    path('patient/book_appointment/', patient_views.book_appointment, name='book_appointment'),
    path('patient/cancle_appointment/<int:pk>/', patient_views.cancel_appointment, name='cancel_appointment'),
    path('patient/appointment_history/', patient_views.appointment_history, name='appointment_history'),
    path('patient/change_password/', patient_views.change_password, name='change_password'),
    path('patient/my_profile/', patient_views.my_profile, name='my_profile'),
    path('patient/generate_feedback/<int:pk>/', patient_views.feedback, name='feedback'),
    path('patient/feedback_history/', patient_views.feedback_history, name='feedback_history'),
    path('patient/medical_history/', patient_views.medical_history, name='medical_history'),
    path('patient/prescriptions/', patient_views.prescription, name='prescription'),
    path('patient/reminders/', patient_views.patient_reminder, name='patient_reminder'),

#  receptionist urls
    path('send/<int:pk>/', receptionist_views.send_reminder, name='send_reminder'),
    path('receptionist/list_reminders/', receptionist_views.list_remainders, name='list_reminders'),
    path('receptionist/view_appointments/', receptionist_views.view_appointments, name='rec_view_appointments'),
    path('receptionist/view_patients/', receptionist_views.view_patients, name='rec_view_patients'),
    path('receptionist/view_contact_us/', receptionist_views.view_contact_us, name='rec_view_contact_us'),
    path('receptionist/monitor_prescriptions/', receptionist_views.monitor_prescriptions, name='rec_monitor_prescriptions'),
    path('receptionist/view_patient_feedback/', receptionist_views.view_patient_feedback, name='rec_view_patient_feedback'),
    path('receptionist/my_profile/', receptionist_views.my_profile, name='rec_my_profile'),
    path('receptionist/change_password/', receptionist_views.change_password, name='rec_change_password'),
]